version: '2'
services:
  elastic:
    image: "elasticsearch:latest"
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
  web:
    build: server
    ports:
      - 4000:4000
    links:
      - "elastic:es"
