version: '2'
services:
  elastic:
    image: "elasticsearch:latest"
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - /data:/user/share/elasticsearch/data
  server:
    build: server
    ports:
      - 4000:4000
    links:
      - "elastic:es"
  web:
    build: image-search-gui
    ports:
      - 8000:8000
    links:
      - "server:app-api"
